#!/bin/sh
# ZeroClaw Docker entrypoint v10 - fix jq parse errors with set -e
# Version 10: Add || true to jq calls to prevent script exit on parse errors

set -e

CONFIG_DIR="${ZEROCLAW_CONFIG_DIR:-/zeroclaw-data/.zeroclaw}"
CONFIG_FILE="${CONFIG_DIR}/config.toml"
WORKSPACE_DIR="${ZEROCLAW_WORKSPACE:-/zeroclaw-data/workspace}"
MOLTSPAY_DIR="/zeroclaw-data/.moltspay"
RUN_USER=65534
RUN_GROUP=65534

echo "[entrypoint v10] Starting as $(id)..."

# ── Fix volume permissions (must run as root) ─────────────────
if [ "$(id -u)" = "0" ]; then
    echo "[entrypoint v10] Fixing /zeroclaw-data ownership for user $RUN_USER..."
    chown -R $RUN_USER:$RUN_GROUP /zeroclaw-data
    echo "[entrypoint v10] Permissions fixed, dropping to user $RUN_USER..."
    
    # Re-exec this script as unprivileged user
    exec gosu $RUN_USER:$RUN_GROUP "$0" "$@"
fi

# ── Everything below runs as user 65534 ───────────────────────
echo "[entrypoint v10] Running as $(id)"

# Ensure directories exist
mkdir -p "$CONFIG_DIR" "$MOLTSPAY_DIR" "$WORKSPACE_DIR"
export HOME="/zeroclaw-data"

# ── Write MoltsPay env vars to workspace/.env for agent shell access ──────
echo "[entrypoint v10] Writing MoltsPay env vars to workspace/.env..."
cat > "$WORKSPACE_DIR/.env" << ENVEOF
# MoltsPay Agent Environment (auto-generated by entrypoint)
AGENT_TOKEN=${AGENT_TOKEN:-}
CREATOR_NAME=${CREATOR_NAME:-}
MOLTSPAY_AGENT_NAME=${MOLTSPAY_AGENT_NAME:-}
MOLTSPAY_AGENT_ID=${MOLTSPAY_AGENT_ID:-}
MOLTSPAY_CREATOR_ID=${MOLTSPAY_CREATOR_ID:-}
MOLTSPAY_API_URL=${MOLTSPAY_API_URL:-https://moltspay.com}
ENVEOF

# ── Initialize MoltsPay wallet if not exists ──────────────────
if [ ! -f "$MOLTSPAY_DIR/wallet.json" ]; then
    echo "[entrypoint v10] Initializing MoltsPay wallet..."
    
    # Initialize wallet (non-interactive, Base chain with explicit limits)
    npx moltspay init --chain base --max-per-tx 100 --max-per-day 1000 2>&1 || {
        echo "[entrypoint v10] Warning: moltspay init failed, will retry later"
    }
    
    # Report wallet address to MoltsPay backend if configured
    if [ -f "$MOLTSPAY_DIR/wallet.json" ] && [ -n "$MOLTSPAY_API_URL" ] && [ -n "$AGENT_TOKEN" ]; then
        WALLET_ADDRESS=$(cat "$MOLTSPAY_DIR/wallet.json" | jq -r '.address' 2>/dev/null) || true
        if [ -n "$WALLET_ADDRESS" ] && [ "$WALLET_ADDRESS" != "null" ]; then
            echo "[entrypoint v10] Reporting wallet address: $WALLET_ADDRESS"
            curl -s -X POST "$MOLTSPAY_API_URL/api/internal/agents/wallet" \
                -H "Authorization: Bearer $AGENT_TOKEN" \
                -H "Content-Type: application/json" \
                -d "{\"address\": \"$WALLET_ADDRESS\"}" || {
                echo "[entrypoint v10] Warning: Failed to report wallet address"
            }
        fi
    fi
else
    echo "[entrypoint v10] MoltsPay wallet already exists"
fi

# ── Fetch and apply spending limit from backend ──────────────────
if [ -n "$MOLTSPAY_API_URL" ] && [ -n "$AGENT_TOKEN" ]; then
    echo "[entrypoint v10] Fetching spending config from backend..."
    CONFIG_RESPONSE=$(curl -s "$MOLTSPAY_API_URL/api/internal/agents/config" \
        -H "Authorization: Bearer $AGENT_TOKEN" 2>/dev/null) || true
    
    if [ -n "$CONFIG_RESPONSE" ]; then
        # Use || true to prevent jq parse errors from crashing the script (set -e)
        SPENDING_LIMIT=$(echo "$CONFIG_RESPONSE" | jq -r '.spending_limit_daily // empty' 2>/dev/null) || true
        if [ -n "$SPENDING_LIMIT" ] && [ "$SPENDING_LIMIT" != "null" ]; then
            echo "[entrypoint v10] Applying spending limit: \$$SPENDING_LIMIT/day"
            npx moltspay config --max-per-day "$SPENDING_LIMIT" 2>&1 || {
                echo "[entrypoint v10] Warning: Failed to apply spending limit"
            }
        fi
    fi
fi

# ── Generate config.toml ──────────────────────────────────────
rm -f "$CONFIG_FILE" 2>/dev/null || true

echo "[entrypoint v10] Generating fresh config.toml..."

# Build Discord config inline if set
DISCORD_INLINE=""
if [ -n "$ZEROCLAW_DISCORD_BOT_TOKEN" ]; then
    echo "[entrypoint v10] Building Discord config..."
    DISCORD_INLINE="discord = { bot_token = \"$ZEROCLAW_DISCORD_BOT_TOKEN\""
    
    if [ -n "$ZEROCLAW_DISCORD_GUILD_ID" ]; then
        DISCORD_INLINE="$DISCORD_INLINE, guild_id = \"$ZEROCLAW_DISCORD_GUILD_ID\""
    fi
    
    # Parse allowed_users - default to ["*"] (allow all) if not set
    if [ -n "$ZEROCLAW_DISCORD_ALLOWED_USERS" ]; then
        # Convert comma-separated list to TOML array
        USERS_ARRAY=$(echo "$ZEROCLAW_DISCORD_ALLOWED_USERS" | sed 's/,/", "/g' | sed 's/^/["/' | sed 's/$/"]/')
        DISCORD_INLINE="$DISCORD_INLINE, allowed_users = $USERS_ARRAY"
    else
        # Default: allow all users
        DISCORD_INLINE="$DISCORD_INLINE, allowed_users = [\"*\"]"
    fi
    
    DISCORD_INLINE="$DISCORD_INLINE, listen_to_bots = false, mention_only = false }"
fi

# Create config with optional Discord inline
cat > "$CONFIG_FILE" << EOF
workspace_dir = "/zeroclaw-data/workspace"
config_path = "/zeroclaw-data/.zeroclaw/config.toml"
api_key = ""
default_provider = "anthropic"
default_model = "claude-sonnet-4-5-20250929"
default_temperature = 0.7

[gateway]
port = 8080
host = "[::]"
allow_public_bind = true
require_pairing = false

[channels_config]
cli = true
message_timeout_secs = 300
$DISCORD_INLINE
EOF

echo "[entrypoint v10] Config generated:"
echo "----------------------------------------"
cat "$CONFIG_FILE"
echo "----------------------------------------"
echo "[entrypoint v10] Starting ZeroClaw..."

exec "$@"
