#!/bin/sh
# ZeroClaw Docker entrypoint v8 - fix moltspay permissions with fallback
# Version 8: Try /zeroclaw-data/.moltspay first, fallback to /tmp if permission denied

CONFIG_DIR="${ZEROCLAW_CONFIG_DIR:-/zeroclaw-data/.zeroclaw}"
CONFIG_FILE="${CONFIG_DIR}/config.toml"
WORKSPACE_DIR="${ZEROCLAW_WORKSPACE:-/zeroclaw-data/workspace}"

echo "[entrypoint v8] Starting..."

# Try to create .moltspay in persistent storage, fallback to /tmp
MOLTSPAY_DIR="/zeroclaw-data/.moltspay"
if ! mkdir -p "$MOLTSPAY_DIR" 2>/dev/null; then
    echo "[entrypoint v8] Cannot create $MOLTSPAY_DIR (permission denied), using /tmp"
    MOLTSPAY_DIR="/tmp/.moltspay"
    mkdir -p "$MOLTSPAY_DIR"
fi
export HOME="$(dirname "$MOLTSPAY_DIR")"
echo "[entrypoint v8] Using MOLTSPAY_DIR=$MOLTSPAY_DIR, HOME=$HOME"

# ── Write MoltsPay env vars to workspace/.env for agent shell access ──────
echo "[entrypoint v8] Writing MoltsPay env vars to workspace/.env..."
cat > "$WORKSPACE_DIR/.env" << ENVEOF
# MoltsPay Agent Environment (auto-generated by entrypoint)
AGENT_TOKEN=${AGENT_TOKEN:-}
CREATOR_NAME=${CREATOR_NAME:-}
MOLTSPAY_AGENT_NAME=${MOLTSPAY_AGENT_NAME:-}
MOLTSPAY_AGENT_ID=${MOLTSPAY_AGENT_ID:-}
MOLTSPAY_CREATOR_ID=${MOLTSPAY_CREATOR_ID:-}
MOLTSPAY_API_URL=${MOLTSPAY_API_URL:-https://moltspay.com}
ENVEOF
echo "[entrypoint v8] Env vars written to $WORKSPACE_DIR/.env"

# ── Initialize MoltsPay wallet if not exists ──────────────────
if [ ! -f "$MOLTSPAY_DIR/wallet.json" ]; then
    echo "[entrypoint v8] Initializing MoltsPay wallet..."
    mkdir -p "$MOLTSPAY_DIR"
    
    # Initialize wallet (non-interactive, Base chain with explicit limits)
    npx moltspay init --chain base --max-per-tx 100 --max-per-day 1000 2>&1 || {
        echo "[entrypoint v8] Warning: moltspay init failed, will retry later"
    }
    
    # Report wallet address to MoltsPay backend if configured
    if [ -f "$MOLTSPAY_DIR/wallet.json" ] && [ -n "$MOLTSPAY_API_URL" ] && [ -n "$AGENT_TOKEN" ]; then
        WALLET_ADDRESS=$(cat "$MOLTSPAY_DIR/wallet.json" | jq -r '.address')
        echo "[entrypoint v8] Reporting wallet address: $WALLET_ADDRESS"
        curl -s -X POST "$MOLTSPAY_API_URL/api/internal/agents/wallet" \
            -H "Authorization: Bearer $AGENT_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"address\": \"$WALLET_ADDRESS\"}" || {
            echo "[entrypoint v8] Warning: Failed to report wallet address"
        }
    fi
else
    echo "[entrypoint v8] MoltsPay wallet already exists"
fi

# ── Fetch and apply spending limit from backend ──────────────────
if [ -n "$MOLTSPAY_API_URL" ] && [ -n "$AGENT_TOKEN" ]; then
    echo "[entrypoint v8] Fetching spending config from backend..."
    CONFIG_RESPONSE=$(curl -s "$MOLTSPAY_API_URL/api/internal/agents/config" \
        -H "Authorization: Bearer $AGENT_TOKEN" 2>/dev/null)
    
    if [ -n "$CONFIG_RESPONSE" ]; then
        SPENDING_LIMIT=$(echo "$CONFIG_RESPONSE" | jq -r '.spending_limit_daily // empty')
        if [ -n "$SPENDING_LIMIT" ] && [ "$SPENDING_LIMIT" != "null" ]; then
            echo "[entrypoint v8] Applying spending limit: \$$SPENDING_LIMIT/day"
            npx moltspay config --max-per-day "$SPENDING_LIMIT" 2>&1 || {
                echo "[entrypoint v8] Warning: Failed to apply spending limit"
            }
        fi
    fi
fi

# Ensure directory exists and remove any existing config
mkdir -p "$CONFIG_DIR"
rm -f "$CONFIG_FILE" 2>/dev/null || true

echo "[entrypoint v3] Generating fresh config.toml..."

# Build Discord config inline if set
DISCORD_INLINE=""
if [ -n "$ZEROCLAW_DISCORD_BOT_TOKEN" ]; then
    echo "[entrypoint v3] Building Discord config..."
    DISCORD_INLINE="discord = { bot_token = \"$ZEROCLAW_DISCORD_BOT_TOKEN\""
    
    if [ -n "$ZEROCLAW_DISCORD_GUILD_ID" ]; then
        DISCORD_INLINE="$DISCORD_INLINE, guild_id = \"$ZEROCLAW_DISCORD_GUILD_ID\""
    fi
    
    # Parse allowed_users - default to ["*"] (allow all) if not set
    if [ -n "$ZEROCLAW_DISCORD_ALLOWED_USERS" ]; then
        # Convert comma-separated list to TOML array
        USERS_ARRAY=$(echo "$ZEROCLAW_DISCORD_ALLOWED_USERS" | sed 's/,/", "/g' | sed 's/^/["/' | sed 's/$/"]/')
        DISCORD_INLINE="$DISCORD_INLINE, allowed_users = $USERS_ARRAY"
    else
        # Default: allow all users
        DISCORD_INLINE="$DISCORD_INLINE, allowed_users = [\"*\"]"
    fi
    
    DISCORD_INLINE="$DISCORD_INLINE, listen_to_bots = false, mention_only = false }"
fi

# Create config with optional Discord inline
cat > "$CONFIG_FILE" << EOF
workspace_dir = "/zeroclaw-data/workspace"
config_path = "/zeroclaw-data/.zeroclaw/config.toml"
api_key = ""
default_provider = "anthropic"
default_model = "claude-sonnet-4-5-20250929"
default_temperature = 0.7

[gateway]
port = 8080
host = "[::]"
allow_public_bind = true
require_pairing = false

[channels_config]
cli = true
message_timeout_secs = 300
$DISCORD_INLINE
EOF

echo "[entrypoint v3] Config generated:"
echo "----------------------------------------"
cat "$CONFIG_FILE"
echo "----------------------------------------"
echo "[entrypoint v3] Starting ZeroClaw..."

exec "$@"
